function pressure = rayleigh_cw_parfor(xdcr, cg, medium, ndiv, f0, dflag)
% Description
%   Calculates pressure field generated by a transducer array in homogeneous media using the Rayleigh-Sommerfeld Integral.
% Usage
%   pressure = rayleigh_cw_parfor(transducer_array, coordinate_grid, medium, ndiv,f0, disp_flag); 
% Arguments
%   transducer_array: A transducer_array.
%   coordinate_grid: A coordinate grid struct like the ones created by set_coordinate_grid.
%   medium: A medium struct like the ones created by set_medium.
%   ndiv: The number of integral points to use.
%   f0: The frequency of the array.
%   disp_flag: Display flag, 1 = display, 0 = suppress.
% Output Parameters
%   pressure: A 3-d array representing the complex pressure at each point in space.
% Notes
%   This function uses the MATLAB Parallel Computing Toolkit to perform the pressure calculation using multiple threads. The speed increase realized by this function is entirely dependent on the number of processor cores present in the computer executing the code. If the Parallel Computing Toolkit is not installed, the function will fail to run.
pressure = 0;
parfor i = 1:size(xdcr,1)*size(xdcr,2)
    pressure = pressure + rayleigh_cw(xdcr(i), cg, medium, ndiv, f0, dflag, 1);
end
end