clear
close all
addpath(fullfile(getenv('ULTRASPECK_ROOT'),'workingFolders\potto\data\subject\gaitStudySMARTLab'));
fullList= { ...
    'S001L1_FAST1','standardBMode'; ...
    'S001L1_FAST2','standardBMode'; ...
    'S001L1_FAST3','standardBMode'; ...
    'S001L1_PF1','standardBMode'; ...
    'S001L1_PF2','standardBMode'; ...
    'S001L1_PF3','standardBMode'; ...
    'S001L1_SLOW1','standardBMode'; ...
    'S001L1_SLOW2','standardBMode'; ...
    'S001L1_VERYSLOW1','standardBMode'; ...
    'S001L1_VERYSLOW2','standardBMode'; ...
    'S001L1_VERYSLOW3','standardBMode'; ...
    'S002L1_FAST1','standardBMode'; ...
    'S002L1_FAST2','standardBMode'; ...
    'S002L1_FAST3','standardBMode'; ...
    'S002L1_PF1','standardBMode'; ...
    'S002L1_PF2','standardBMode'; ...
    'S002L1_PF3','standardBMode'; ...
    'S002L1_SLOW1','standardBMode'; ...
    'S002L1_SLOW2','standardBMode'; ...
    'S002L1_SLOW3','standardBMode'; ...
    'S002L1_VERYSLOW1','standardBMode'; ...
    'S002L1_VERYSLOW2','standardBMode'; ...
    'S002L1_VERYSLOW3','standardBMode'; ...
    'S003L1_FAST1','standardBMode'; ...
    'S003L1_FAST2','standardBMode'; ...
    'S003L1_FAST3','standardBMode'; ...
    'S003L1_PF1','standardBMode'; ...
    'S003L1_PF2','standardBMode'; ...
    'S003L1_PF3','standardBMode'; ...
    'S003L1_SLOW1','standardBMode'; ...
    'S003L1_SLOW2','standardBMode'; ...
    'S003L1_SLOW3','standardBMode'; ...
    'S003L1_VERYSLOW1','standardBMode'; ...
    'S003L1_VERYSLOW2','standardBMode'; ...
    'S003L1_VERYSLOW3','standardBMode'; ...
    'S003L1_MVIC1','standardBMode'; ...
    'S003L1_MVIC2','standardBMode'; ...
    'S003L1_MVIC3','standardBMode'; ...
    'S003L1_MVIC4','standardBMode'; ...
    'S004L1_Fast1','standardBMode'; ...
    'S004L1_Fast2','standardBMode'; ...
    'S004L1_FAST3','standardBMode'; ...
    'S004L1_MVIC1','standardBMode'; ...
    'S004L1_MVIC2','standardBMode'; ...
    'S004L1_MVIC3','standardBMode'; ...
    'S004L1_MVIC4','standardBMode'; ...
    'S004L1_PF1','standardBMode'; ...
    'S004L1_PF2','standardBMode'; ...
    'S004L1_PF3','standardBMode'; ...
    'S004L1_SLOW1','standardBMode'; ...
    'S004L1_SLOW2','standardBMode'; ...
    'S004L1_SLOW3','standardBMode'; ...
    'S004L1_VERYSLOW1','standardBMode'; ...
    'S004L1_VERYSLOW2','standardBMode'; ...
    'S004L1_VERYSLOW3','standardBMode'; ...
    'S005L2_FAST1','standardBMode'; ...
    'S005L2_FAST2','standardBMode'; ...
    'S005L2_FAST3','standardBMode'; ...
    'S005L2_MVIC1','standardBMode'; ...
    'S005L2_MVIC2','standardBMode'; ...
    'S005L2_MVIC3','standardBMode'; ...
    'S005L2_MVIC4','standardBMode'; ...
    'S005L2_PF1','standardBMode'; ...
    'S005L2_PF2','standardBMode'; ...
    'S005L2_PF3','standardBMode'; ...
    'S005L2_SLOW1','standardBMode'; ...
    'S005L2_SLOW2','standardBMode'; ...
    'S005L2_SLOW3','standardBMode'; ...
    'S005L2_VERYSLOW1','standardBMode'; ...
    'S005L2_VERYSLOW2','standardBMode'; ...
    'S005L2_VERYSLOW3','standardBMode'; ...
    'S006L1_FAST1','standardBMode'; ...
    'S006L1_FAST2','standardBMode'; ...
    'S006L1_FAST3','standardBMode'; ...
    'S006L1_PF1','standardBMode'; ...
    'S006L1_PF2','standardBMode'; ...
    'S006L1_PF3','standardBMode'; ...
    'S006L1_SLOW1','standardBMode'; ...
    'S006L1_SLOW2','standardBMode'; ...
    'S006L1_SLOW3','standardBMode'; ...
    'S006L1_VERYSLOW1','standardBMode'; ...
    'S006L1_VERYSLOW2','standardBMode'; ...
    'S006L1_VERYSLOW3','standardBMode'; ...
    'S007L1_FAST1','standardBMode'; ...
    'S007L1_FAST2','standardBMode'; ...
    'S007L1_FAST3','standardBMode'; ...
    'S007L1_MVIC1','standardBMode'; ...
    'S007L1_MVIC2','standardBMode'; ...
    'S007L1_MVIC3','standardBMode'; ...
    'S007L1_MVIC4','standardBMode'; ...
    'S007L1_PF1','standardBMode'; ...
    'S007L1_PF2','standardBMode'; ...
    'S007L1_PF3','standardBMode'; ...
    'S007L1_SLOW1','standardBMode'; ...
    'S007L1_SLOW2','standardBMode'; ...
    'S007L1_SLOW3','standardBMode'; ...
    'S007L1_VERYSLOW1','standardBMode'; ...
    'S007L1_VERYSLOW2','standardBMode'; ...
    'S007L1_VERYSLOW3','standardBMode'; ...
    
    };


trialData=loadMetadata([fullList{13,1} '.m']);
dataBlockObj=getCollection(trialData,'col_ultrasound_bmode');

%% Process the entire region
%[xmin_lateral ymin_axial width_lateral height_axial]
%filterRegion=[264, 45, (303-264+1), (144 - 45 +1)];
%filterRegion=[264, 60, (303-264+1), (20)];



frameIndexes=9;
weightAlpha = 30;
weightTau = 0.5;
runLength = 20;
accetableCutoffPercentage = 0.005;
processedBlk = dataBlockObj.blockData;
filterRegion=[215, 1, 215, size(processedBlk,1)];

[processedBlk, svdSpectrum, svdWeightedSpectrum, weightSpectrum] = svdFilter(processedBlk, filterRegion, frameIndexes, weightAlpha, weightTau, runLength, accetableCutoffPercentage);
% rootDirectory=fullfile(getenv('DATA_ULTRASOUND'),'MyStudyUS');
%% Show the SVD spectrum

%normSvdSpectrum=(svdSpectrum./repmat(sum(svdSpectrum), size(svdSpectrum,1),1));
normSvdSpectrum = bsxfun(@(x,y) x/y, svdSpectrum,sum(svdSpectrum));

figure;
waterfall(frameIndexes, filterRegion(1) + [0:(filterRegion(3)-1)],normSvdSpectrum')
title('normSvdSpectrum')
xlabel('Frame (N/A)')
ylabel('Lateral  (pel)')

figure;
waterfall(frameIndexes, filterRegion(1) + [0:(filterRegion(3)-1)],weightSpectrum')
title('Weights')
xlabel('Frame (N/A)')
ylabel('Lateral  (pel)')

figure;
waterfall(frameIndexes, filterRegion(1) + [0:(filterRegion(3)-1)],svdSpectrum')
title('Preweighted Spectrum')
xlabel('Frame (N/A)')
ylabel('Lateral  (pel)')

figure;
waterfall(frameIndexes, filterRegion(1) + [0:(filterRegion(3)-1)],(svdWeightedSpectrum)')
title('Weighted Spectrum')
xlabel('Frame (N/A)')
ylabel('Lateral  (pel)')

%%
figure;
plot(log10(sqrt(sum(svdSpectrum.^2))))
hold on
plot(log10(sqrt(sum((svdWeightedSpectrum).^2))),'r:')
title('Comparing spectral power between weighted and unweighted ROI');
legend('Preweighted Spectrum','Weighted Spectrum');
xlabel('Frame (N/A)')
ylabel('Power  (dB)')

%%
testFrameIndex=frameIndexes(5); %round(mean(frameIndexes));

imBefore = dataBlockObj.blockData(:,:,testFrameIndex);
imAfter = processedBlk(:,:,testFrameIndex);

imageWidth=[200 450];
imageWidth=[];

figure;
ax=[];
ax(1)=subplot(1,3,1);
imagesc(imBefore.^0.5); colormap(gray(256));
if ~isempty(imageWidth)
    xlim(imageWidth)
end
valLim=caxis;
title(['Frame ' num2str(testFrameIndex) ' before processing'])
xlabel('lateral (pel)')
ylabel('axial (pel)')
axis('square')

ax(end+1)=subplot(1,3,2);
imagesc(abs(imAfter).^0.5); colormap(gray(256));
if ~isempty(imageWidth)
    xlim(imageWidth)
end
caxis(valLim);
title(['After processing (\alpha = ' num2str(weightAlpha) ', \tau = ' num2str(weightTau) ')'])
xlabel('lateral (pel)')
ylabel('axial (pel)')
axis('square')

ax(end+1)=subplot(1,3,3);
imagesc(abs(imBefore-imAfter).^0.5); colormap(gray(256));
caxis(valLim);
title(['Difference'])
xlabel('lateral (pel)')
ylabel('axial (pel)')
axis('square')
linkaxes(ax,'xy')

if ~isempty(imageWidth)
    axis([219  431   11  131])
end

if false
    im=squeeze(dataBlockObj.blockData(:,300,:));
    figure;
    imagesc(im); colormap(gray(256))
end