%close all
clear
%clear functions



switch(getenv('USERNAME'))
    case 'potto'
        %shearWaveAnalysisAreaCalc(loadRFData('W:\MTrP_Ultrasonix_Data_GMU\MTRP015_V1\07-28-2011-Generic\14-51-03.rf'), ...
%         sh=swGUI(swCase('C:\Documents and Settings\potto\My Documents\localData\ShearwaveCache\14-51-03.rf'), ...            
%             'startBlock',100, ...
%             'maxMemoryForArrayInSamples',1500*32*128,'shearwaveGeneratorPosition',[]);
        sh=swGUI(swCase('W:\MTrP_Ultrasonix_Data_GMU\PHANTOM_0506\05-06-2011-MSK\IV_200_T1.rf'), ...            
            'startBlock',100, ...
            'maxMemoryForArrayInSamples',1500*32*128,'shearwaveGeneratorPosition',[]);
        
    case 'dturo'
        sh=swGUI(swCase, ...            
            'startBlock',100, ...
            'maxMemoryForArrayInSamples',1500*32*128,'shearwaveGeneratorPosition',[]);
    otherwise
        sh=swGUI(swCase, ...            
            'startBlock',100, ...
            'maxMemoryForArrayInSamples',1500*32*128,'shearwaveGeneratorPosition',[]);
end

